
CREATE TABLE TurmasDaGrade(
	grade INTEGER NOT NULL,
	turma INTEGER NOT NULL,
	
	CONSTRAINT pkTG_turmas_grade PRIMARY KEY (grade, turma),
    CONSTRAINT fkTG_grade FOREIGN KEY (grade) REFERENCES GradeHoraria(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fkTG_turma FOREIGN KEY (turma) REFERENCES Turma(nro) ON UPDATE CASCADE ON DELETE CASCADE
	)ENGINE=InnoDB;	
	